In [1]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec
import gensim
from collections import Counter
import ast

In [2]:
df = pd.read_csv("merged_data_all_labeled.csv")


# Tweet depresif bernilai 1
df["label"] = df["label"].replace("Positif", 1)
# Tweet non depresif bernilai 0
df["label"] = df["label"].replace("Negatif", 0)
df

full_text      username  label
0    ['material', 'contoh', 'rumah', 'old', 'crawfo...      barkahha      0
1    ['wajah', 'tangis', 'kerasjempol', 'ke', 'atas...   ccherry0831      1
2    ['city', 'sangat', 'rekornya', 'rasa', 'ambil'...     kopobased      0
3    ['lateral', 'tere', 'jus', 'human', 'respons',...  sebutajadono      1
4    ['info', 'ada', 'penjuru', 'jawa', 'kata', 'wa...   energifoton      1
..                                                 ...           ...    ...
179   ['pikir', 'pikir', 'rencana', 'madara', 'buruk']        yusepf      0
180  ['di', 'qrt', 'sapa', 'tau', 'besok', 'dapat',...   yuyuanyuyun      1
181  ['enggak', 'erti', 'rasa', 'sendiri', 'enggak'...    zephaniaky      1
182  ['gable', 'begitu', 'ya', 'memang', 'sampai', ...        zsxndr      1
183  ['cerita', 'kemarin', 'teman', 'cowok', 'antar...        zxrayy      1

[184 rows x 3 columns]

In [3]:
def convert_string_to_list(string_representation):
    return ast.literal_eval(string_representation)

df['full_text'] = df['full_text'].apply(lambda x: convert_string_to_list(x))
df

full_text      username  label
0    [material, contoh, rumah, old, crawford, saja,...      barkahha      0
1    [wajah, tangis, kerasjempol, ke, atas, warna, ...   ccherry0831      1
2    [city, sangat, rekornya, rasa, ambil, makula, ...     kopobased      0
3    [lateral, tere, jus, human, respons, agak, gow...  sebutajadono      1
4    [info, ada, penjuru, jawa, kata, wajah, merenu...   energifoton      1
..                                                 ...           ...    ...
179             [pikir, pikir, rencana, madara, buruk]        yusepf      0
180  [di, qrt, sapa, tau, besok, dapat, did, benar,...   yuyuanyuyun      1
181  [enggak, erti, rasa, sendiri, enggak, erti, ra...    zephaniaky      1
182  [gable, begitu, ya, memang, sampai, begah, drt...        zsxndr      1
183  [cerita, kemarin, teman, cowok, antar, barang,...        zxrayy      1

[184 rows x 3 columns]

## Splitting Dataset

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
X = df["full_text"].tolist()

In [ ]:
X

In [7]:
y = df["label"].tolist()
y

[0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Word2Vec CBOW

In [9]:
cbow_model_path = "cbow_wiki_word2vec_gensim3.model"

In [10]:
model_skipgram = gensim.models.Word2Vec.load(cbow_model_path)

In [11]:
print(model_skipgram.wv['ko'])

[ 0.20935215 -0.16600738  1.2337825  -1.0780579   1.309842   -0.03902972
 -0.18744561  1.5011691   0.2272823  -0.79634684  0.79760253 -1.870791
  0.8173654   2.4760776  -1.116784   -0.04398677 -0.58513397 -1.7416074
  1.2446173  -0.5805072   1.0857346   0.3255919  -0.10434823 -0.0990589
 -1.1890175  -0.15064307 -0.92485243  1.2751228   0.55533475 -0.3823779
  0.07142598  0.3207153   1.6426266   0.68556666  1.2785733   1.7584764
 -0.8360852  -1.1685948  -1.4860712   0.84711474  1.0728495  -0.18352571
 -0.9451292  -0.31151468 -0.05614884  1.0455874   0.3254332  -0.48109275
  1.7288772  -1.2869307  -0.6751335   0.9775355   1.6497294  -0.44633645
 -0.23993957 -1.1618081  -0.7851836  -0.7395274  -1.3922937   1.5709502
  0.36041752 -0.02587246 -0.49870482 -0.11910601 -2.2857928  -0.94179296
 -0.75154686  0.54059154  0.05110457  0.4436739   0.13321163 -0.42028686
  1.4089887  -1.2373168  -0.47844    -0.47982705 -1.3354539  -0.81545097
 -1.1358294   1.508088   -0.09423823 -0.9379656  -0.609270

In [12]:
similarity = model_skipgram.wv.most_similar("indonesia", topn=10)
print(similarity)

[('nusantara', 0.6011855602264404), ('malaysia', 0.5389484763145447), ('singapura', 0.5067294239997864), ('jakarta', 0.49905991554260254), ('yogyakarta', 0.4980625808238983), ('riau', 0.49532872438430786), ('bandung', 0.4908183515071869), ('bali', 0.4890998601913452), ('makassar', 0.48331037163734436), ('indonesian', 0.4822588264942169)]


In [13]:
# Ubah semua token dalam data menjadi representasi vektor dengan Word2Vec
def sent_vec(sent):
    vector_size = model_skipgram.wv.vector_size
    wv_res = np.zeros(vector_size)
    # print(wv_res)
    ctr = 1
    for w in sent:
        if w in model_skipgram.wv:
            ctr += 1
            wv_res += model_skipgram.wv[w]
    wv_res = wv_res/ctr
    return wv_res


In [14]:
X_trainvec =[]
X_testvec = []

In [15]:
for i in range(len(X_train)):
    X_trainvec.append(sent_vec(X_train[i]))
X_trainvec

[array([-1.65230089e-01,  1.58278503e-01,  2.75328996e-01, -3.70620244e-01,
        -2.88222805e-01, -9.51812413e-02,  4.65065044e-01,  3.72509923e-02,
        -8.97195481e-02, -2.91366451e-02,  6.00484538e-02, -4.81919467e-01,
        -8.96188026e-02,  4.48113079e-01, -1.71760973e-01, -1.21148572e-01,
        -2.68930991e-01,  5.68542954e-02,  5.95197639e-01, -4.15704123e-01,
         2.28155732e-01, -1.00361898e-01, -6.62225252e-01,  4.41382561e-01,
        -7.17546232e-01,  6.51717296e-02, -3.32466718e-01, -6.83868066e-01,
         2.11183135e-01, -1.96190450e-01, -2.14849161e-01, -2.89887159e-01,
        -3.05136186e-01,  1.12202449e-01,  2.69528740e-01, -2.78470410e-01,
        -2.48823207e-01, -4.07462377e-01, -3.09373700e-01,  4.00088667e-01,
        -9.19175244e-02,  3.59945710e-01,  2.45576718e-01, -3.23786017e-01,
        -3.78857774e-01, -1.33992933e-01, -3.30440685e-01, -5.34724755e-01,
         4.06953354e-01, -2.03767565e-01,  6.52742903e-02,  3.98608941e-01,
         6.7

In [16]:
for i in range(len(X_test)):
    X_testvec.append(sent_vec(X_test[i]))
X_testvec

[array([-0.15782229,  0.09918902,  0.46426185, -0.4609776 , -0.43770439,
        -0.0801028 ,  0.63625522,  0.05785471, -0.08154369, -0.03500234,
        -0.05244367, -0.79691607, -0.23112891,  0.28221578, -0.02370436,
        -0.04863621, -0.36517425,  0.11858387,  0.73995974, -0.51996778,
         0.23427121, -0.21189642, -0.75688571,  0.31710431, -0.72889377,
         0.36263558, -0.43188565, -0.70251567,  0.23370512, -0.14609416,
        -0.44177952, -0.42827853, -0.26205504,  0.02541463,  0.20242462,
        -0.35534299, -0.06185315, -0.29089699, -0.26483729,  0.45174971,
        -0.0740971 ,  0.42732834,  0.21387769, -0.27123927, -0.43315459,
         0.11581977, -0.38836818, -0.50300947,  0.17687994, -0.24770349,
         0.03775253,  0.41320645,  0.67108668,  0.11211638, -0.06761874,
        -0.12498901, -0.51657941,  0.11258324,  0.5420885 ,  0.26170703,
         0.45821141, -0.17396189,  0.07324289, -0.57422539,  0.21879946,
        -0.42246806,  0.02496251, -0.08825539, -0.1

In [17]:
print("Jumlah data X_train :", len(X_trainvec))
print("Jumlah data X_test :", len(X_testvec))

Jumlah data X_train : 128
Jumlah data X_test : 56


In [18]:
print("Jumlah data y_train :", len(y_train))
print("Jumlah data y_test :", len(y_test))

Jumlah data y_train : 128
Jumlah data y_test : 56


# Implementation

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn import model_selection
from sklearn import preprocessing
from sklearn.metrics import classification_report, confusion_matrix

## Decision Tree

In [20]:
hasil_params=[]
hasil_akurasi=[]
hasil_all=[]

In [21]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['gini'],
              'max_depth': [None],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'gini', 'max_depth': None}
Accuracy: 0.44642857142857145
Classification Report:
               precision    recall  f1-score   support

           0       0.36      0.43      0.39        23
           1       0.54      0.45      0.49        33

    accuracy                           0.45        56
   macro avg       0.45      0.44      0.44        56
weighted avg       0.46      0.45      0.45        56

F1 Score: 0.45
Confusion Matrix:
 [[10 13]
 [18 15]]


In [22]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['entropy'],
              'max_depth': [10],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'entropy', 'max_depth': 10}
Accuracy: 0.5357142857142857
Classification Report:
               precision    recall  f1-score   support

           0       0.43      0.39      0.41        23
           1       0.60      0.64      0.62        33

    accuracy                           0.54        56
   macro avg       0.51      0.51      0.51        56
weighted avg       0.53      0.54      0.53        56

F1 Score: 0.53
Confusion Matrix:
 [[ 9 14]
 [12 21]]


In [23]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['entropy'],
              'max_depth': [20],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'entropy', 'max_depth': 20}
Accuracy: 0.5535714285714286
Classification Report:
               precision    recall  f1-score   support

           0       0.45      0.43      0.44        23
           1       0.62      0.64      0.63        33

    accuracy                           0.55        56
   macro avg       0.54      0.54      0.54        56
weighted avg       0.55      0.55      0.55        56

F1 Score: 0.55
Confusion Matrix:
 [[10 13]
 [12 21]]


In [24]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['entropy'],
              'max_depth': [30],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'entropy', 'max_depth': 30}
Accuracy: 0.5
Classification Report:
               precision    recall  f1-score   support

           0       0.40      0.43      0.42        23
           1       0.58      0.55      0.56        33

    accuracy                           0.50        56
   macro avg       0.49      0.49      0.49        56
weighted avg       0.51      0.50      0.50        56

F1 Score: 0.5
Confusion Matrix:
 [[10 13]
 [15 18]]


In [25]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['entropy'],
              'max_depth': [40],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'entropy', 'max_depth': 40}
Accuracy: 0.5357142857142857
Classification Report:
               precision    recall  f1-score   support

           0       0.43      0.39      0.41        23
           1       0.60      0.64      0.62        33

    accuracy                           0.54        56
   macro avg       0.51      0.51      0.51        56
weighted avg       0.53      0.54      0.53        56

F1 Score: 0.53
Confusion Matrix:
 [[ 9 14]
 [12 21]]


In [26]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['entropy'],
              'max_depth': [50],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'entropy', 'max_depth': 50}
Accuracy: 0.5357142857142857
Classification Report:
               precision    recall  f1-score   support

           0       0.43      0.43      0.43        23
           1       0.61      0.61      0.61        33

    accuracy                           0.54        56
   macro avg       0.52      0.52      0.52        56
weighted avg       0.54      0.54      0.54        56

F1 Score: 0.54
Confusion Matrix:
 [[10 13]
 [13 20]]


In [27]:
for i in range(len(hasil_params)):
    print(hasil_params[i])
    print("akurasi ",hasil_akurasi[i])
    print("f1 Score",hasil_all[i])


{'criterion': 'gini', 'max_depth': None}
akurasi  0.44642857142857145
f1 Score 0.45
{'criterion': 'entropy', 'max_depth': 10}
akurasi  0.5357142857142857
f1 Score 0.53
{'criterion': 'entropy', 'max_depth': 20}
akurasi  0.5535714285714286
f1 Score 0.55
{'criterion': 'entropy', 'max_depth': 30}
akurasi  0.5
f1 Score 0.5
{'criterion': 'entropy', 'max_depth': 40}
akurasi  0.5357142857142857
f1 Score 0.53
{'criterion': 'entropy', 'max_depth': 50}
akurasi  0.5357142857142857
f1 Score 0.54
