In [1]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec
import gensim
from collections import Counter
import ast

In [2]:
df = pd.read_csv("merged_data_all_labeled.csv")


# Tweet depresif bernilai 1
df["label"] = df["label"].replace("Positif", 1)
# Tweet non depresif bernilai 0
df["label"] = df["label"].replace("Negatif", 0)
df

full_text      username  label
0    ['material', 'contoh', 'rumah', 'old', 'crawfo...      barkahha      0
1    ['wajah', 'tangis', 'kerasjempol', 'ke', 'atas...   ccherry0831      1
2    ['city', 'sangat', 'rekornya', 'rasa', 'ambil'...     kopobased      0
3    ['lateral', 'tere', 'jus', 'human', 'respons',...  sebutajadono      1
4    ['info', 'ada', 'penjuru', 'jawa', 'kata', 'wa...   energifoton      1
..                                                 ...           ...    ...
179   ['pikir', 'pikir', 'rencana', 'madara', 'buruk']        yusepf      0
180  ['di', 'qrt', 'sapa', 'tau', 'besok', 'dapat',...   yuyuanyuyun      1
181  ['enggak', 'erti', 'rasa', 'sendiri', 'enggak'...    zephaniaky      1
182  ['gable', 'begitu', 'ya', 'memang', 'sampai', ...        zsxndr      1
183  ['cerita', 'kemarin', 'teman', 'cowok', 'antar...        zxrayy      1

[184 rows x 3 columns]

In [3]:
def convert_string_to_list(string_representation):
    return ast.literal_eval(string_representation)

df['full_text'] = df['full_text'].apply(lambda x: convert_string_to_list(x))
df

full_text      username  label
0    [material, contoh, rumah, old, crawford, saja,...      barkahha      0
1    [wajah, tangis, kerasjempol, ke, atas, warna, ...   ccherry0831      1
2    [city, sangat, rekornya, rasa, ambil, makula, ...     kopobased      0
3    [lateral, tere, jus, human, respons, agak, gow...  sebutajadono      1
4    [info, ada, penjuru, jawa, kata, wajah, merenu...   energifoton      1
..                                                 ...           ...    ...
179             [pikir, pikir, rencana, madara, buruk]        yusepf      0
180  [di, qrt, sapa, tau, besok, dapat, did, benar,...   yuyuanyuyun      1
181  [enggak, erti, rasa, sendiri, enggak, erti, ra...    zephaniaky      1
182  [gable, begitu, ya, memang, sampai, begah, drt...        zsxndr      1
183  [cerita, kemarin, teman, cowok, antar, barang,...        zxrayy      1

[184 rows x 3 columns]

## Splitting Dataset

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
X = df["full_text"].tolist()

In [ ]:
X

In [7]:
y = df["label"].tolist()
y

[0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Word2Vec Skipgram

In [9]:
skipgram_model_path = "skipgram_wiki_word2vec_gensim3.model"

In [10]:
model_skipgram = gensim.models.Word2Vec.load(skipgram_model_path)

In [11]:
print(model_skipgram.wv['ko'])

[ 0.40372443 -0.3694866   0.20410976 -0.04198106  0.12128536 -0.39556536
  0.01197265  0.20870921 -0.196898    0.11195729  0.32668257 -0.71916676
  0.0519979  -0.12240642 -0.28971693  0.23897061 -0.11424562 -0.06959187
  0.30641815 -0.3102607   0.34471944  0.13604736  0.00174567  0.37357327
 -0.18831494  0.21847735 -0.08607562  0.07179521  0.08201333 -0.10415148
 -0.21061943 -0.22696912  0.01248509 -0.35231447 -0.0764681  -0.07654975
 -0.4107089   0.16962358 -0.6798518  -0.7394962  -0.14642675  0.22804861
 -0.26038766 -0.03977719 -0.15593246 -0.21950175 -0.19337389  0.17188786
  0.3171345   0.05514578 -0.29335147  0.2468579   0.14726937 -0.4982972
  0.3287454  -0.62560356  0.38363877  0.08844924  0.16576208 -0.10881267
  0.21344577 -0.12723696  0.2158898  -0.36280146 -0.18409395  0.16636044
 -0.36395785 -0.33458894 -0.1909224  -0.38231653 -0.1727317   0.18273105
  0.14387667 -0.04475836  0.05418052  0.28226173 -0.29826647 -0.02447118
 -0.07120833 -0.36335114  0.25206771 -0.07108528 -0.

In [12]:
similarity = model_skipgram.wv.most_similar("indonesia", topn=10)
print(similarity)

[('indoensia', 0.6479810476303101), ('indoneia', 0.6447494626045227), ('lndonesia', 0.6304401755332947), ('indonsia', 0.628505527973175), ('terinspiratif', 0.626674234867096), ('indonesa', 0.6176382899284363), ('inonesia', 0.6163718104362488), ('indonesi', 0.6129399538040161), ('woobiz', 0.6065080165863037), ('ipemi', 0.6018319129943848)]


In [13]:
# Ubah semua token dalam data menjadi representasi vektor dengan Word2Vec
def sent_vec(sent):
    vector_size = model_skipgram.wv.vector_size
    wv_res = np.zeros(vector_size)
    # print(wv_res)
    ctr = 1
    for w in sent:
        if w in model_skipgram.wv:
            ctr += 1
            wv_res += model_skipgram.wv[w]
    wv_res = wv_res/ctr
    return wv_res


In [14]:
X_trainvec =[]
X_testvec = []

In [15]:
for i in range(len(X_train)):
    X_trainvec.append(sent_vec(X_train[i]))
X_trainvec

[array([-2.21868145e-01, -2.98291649e-02, -5.70117134e-02, -1.48097058e-02,
        -1.50552913e-02, -2.20734158e-01, -1.51867646e-02,  2.24336042e-01,
         8.70519897e-02, -1.16166991e-01,  8.07491884e-02, -4.75542287e-02,
         4.96103942e-02,  9.94479282e-02, -1.12718131e-01, -1.82666806e-01,
        -7.39225570e-02, -8.31884568e-02,  1.09405381e-01, -2.54296711e-01,
         9.26247780e-02,  4.91031612e-02, -1.23490552e-01,  1.99003903e-01,
        -2.10851651e-01, -1.89798641e-01, -8.74381728e-02, -2.11747206e-01,
        -6.65385216e-02, -1.78673929e-01,  7.24802646e-02,  1.50436067e-01,
         1.28469127e-01,  1.78954319e-01, -4.92230211e-02,  1.40325977e-01,
         1.58380540e-01, -1.73737217e-01, -1.54816720e-01, -8.42560986e-02,
         3.44188873e-02,  8.16725378e-03,  7.59120169e-02, -4.59228373e-02,
        -9.57760161e-03,  3.21891752e-01,  1.84853944e-02,  4.04171620e-02,
         1.38515841e-01, -1.06565194e-01,  2.71578758e-01,  8.17152649e-02,
         1.6

In [16]:
for i in range(len(X_test)):
    X_testvec.append(sent_vec(X_test[i]))
X_testvec

[array([-2.79147181e-01, -5.56637934e-03, -3.80841305e-02, -8.40451816e-03,
        -3.69072622e-03, -1.98264421e-01,  1.53358996e-02,  2.56153258e-01,
         9.04604116e-02, -1.20187240e-01,  8.51904312e-02, -8.66222496e-02,
         3.10225408e-02,  4.69084939e-02, -1.09511227e-01, -1.81725644e-01,
        -1.03757126e-01, -1.03766087e-01,  1.73657358e-01, -2.71912768e-01,
         6.41449631e-02,  4.38861582e-02, -1.10824295e-01,  1.84846483e-01,
        -2.45747781e-01, -1.44068399e-01, -9.29502556e-02, -2.25668117e-01,
        -4.58587951e-02, -2.20807229e-01,  8.15559939e-02,  1.67000687e-01,
         1.36438730e-01,  1.55064160e-01, -3.88425049e-02,  1.43891864e-01,
         2.09863898e-01, -1.88420458e-01, -1.51215887e-01, -7.75088608e-02,
         8.94706905e-02,  3.83216308e-02,  8.90561852e-02, -4.65786962e-02,
        -2.74376099e-02,  3.57190993e-01, -1.18867993e-03,  7.18041617e-02,
         1.40257973e-01, -1.05501684e-01,  3.04206695e-01,  8.38255312e-02,
         1.7

In [17]:
print("Jumlah data X_train :", len(X_trainvec))
print("Jumlah data X_test :", len(X_testvec))

Jumlah data X_train : 128
Jumlah data X_test : 56


In [18]:
print("Jumlah data y_train :", len(y_train))
print("Jumlah data y_test :", len(y_test))

Jumlah data y_train : 128
Jumlah data y_test : 56


# Implementation

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn import model_selection
from sklearn import preprocessing
from sklearn.metrics import classification_report, confusion_matrix

## Decision Tree

In [20]:
hasil_params=[]
hasil_akurasi=[]
hasil_all=[]

In [21]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['gini'],
              'max_depth': [None],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'gini', 'max_depth': None}
Accuracy: 0.5178571428571429
Classification Report:
               precision    recall  f1-score   support

           0       0.42      0.48      0.45        23
           1       0.60      0.55      0.57        33

    accuracy                           0.52        56
   macro avg       0.51      0.51      0.51        56
weighted avg       0.53      0.52      0.52        56

F1 Score: 0.52
Confusion Matrix:
 [[11 12]
 [15 18]]


In [22]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['gini'],
              'max_depth': [10],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'gini', 'max_depth': 10}
Accuracy: 0.4642857142857143
Classification Report:
               precision    recall  f1-score   support

           0       0.32      0.26      0.29        23
           1       0.54      0.61      0.57        33

    accuracy                           0.46        56
   macro avg       0.43      0.43      0.43        56
weighted avg       0.45      0.46      0.45        56

F1 Score: 0.45
Confusion Matrix:
 [[ 6 17]
 [13 20]]


In [23]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['entropy'],
              'max_depth': [20],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'entropy', 'max_depth': 20}
Accuracy: 0.5357142857142857
Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.52      0.48        23
           1       0.62      0.55      0.58        33

    accuracy                           0.54        56
   macro avg       0.53      0.53      0.53        56
weighted avg       0.55      0.54      0.54        56

F1 Score: 0.54
Confusion Matrix:
 [[12 11]
 [15 18]]


In [24]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['gini'],
              'max_depth': [30],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'gini', 'max_depth': 30}
Accuracy: 0.44642857142857145
Classification Report:
               precision    recall  f1-score   support

           0       0.32      0.30      0.31        23
           1       0.53      0.55      0.54        33

    accuracy                           0.45        56
   macro avg       0.42      0.42      0.42        56
weighted avg       0.44      0.45      0.44        56

F1 Score: 0.44
Confusion Matrix:
 [[ 7 16]
 [15 18]]


In [25]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['gini'],
              'max_depth': [40],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'gini', 'max_depth': 40}
Accuracy: 0.5
Classification Report:
               precision    recall  f1-score   support

           0       0.40      0.43      0.42        23
           1       0.58      0.55      0.56        33

    accuracy                           0.50        56
   macro avg       0.49      0.49      0.49        56
weighted avg       0.51      0.50      0.50        56

F1 Score: 0.5
Confusion Matrix:
 [[10 13]
 [15 18]]


In [26]:
# Standarisasi fitur yang digunakan
scaler = preprocessing.StandardScaler()
X_train_scaled = scaler.fit_transform(X_trainvec)
X_test_scaled = scaler.transform(X_testvec)

# Hyperparameter yang akan digunakan untuk menentukan parameter terbaik
param_grid = {'criterion': ['gini'],
              'max_depth': [50],
              }

# Decision Tree Classifier
dt_classifier = DecisionTreeClassifier()

# Grid Search untuk mencari parameter terbaik
grid_search = model_selection.GridSearchCV(dt_classifier, param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Parameter terbaik
best_params_dt = grid_search.best_params_

# Train Decision Tree menggunakan parameter terbaik
dt_classifier = DecisionTreeClassifier(**best_params_dt)
dt_classifier.fit(X_train_scaled, y_train)

# Evaluasi model yang dibuat
X_test_scaled = scaler.transform(X_testvec)
y_pred = dt_classifier.predict(X_test_scaled)
accuracy = dt_classifier.score(X_test_scaled, y_test)

# Akurasi model
print(best_params_dt)
print("Accuracy:", accuracy)

# Calculate precision, recall, and F1-score
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)
# Extract F1-score from the classification report
f1_score_value = float(classification_rep.split()[-2])

# Print F1-score
print("F1 Score:", f1_score_value)

# Calculate confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)
hasil_params.append(best_params_dt)
hasil_akurasi.append(accuracy)
hasil_all.append(f1_score_value)

{'criterion': 'gini', 'max_depth': 50}
Accuracy: 0.5357142857142857
Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.52      0.48        23
           1       0.62      0.55      0.58        33

    accuracy                           0.54        56
   macro avg       0.53      0.53      0.53        56
weighted avg       0.55      0.54      0.54        56

F1 Score: 0.54
Confusion Matrix:
 [[12 11]
 [15 18]]


In [27]:
for i in range(len(hasil_params)):
    print(hasil_params[i])
    print("akurasi ",hasil_akurasi[i])
    print("f1 Score",hasil_all[i])


{'criterion': 'gini', 'max_depth': None}
akurasi  0.5178571428571429
f1 Score 0.52
{'criterion': 'gini', 'max_depth': 10}
akurasi  0.4642857142857143
f1 Score 0.45
{'criterion': 'entropy', 'max_depth': 20}
akurasi  0.5357142857142857
f1 Score 0.54
{'criterion': 'gini', 'max_depth': 30}
akurasi  0.44642857142857145
f1 Score 0.44
{'criterion': 'gini', 'max_depth': 40}
akurasi  0.5
f1 Score 0.5
{'criterion': 'gini', 'max_depth': 50}
akurasi  0.5357142857142857
f1 Score 0.54
